<?php

/**
 * @file
 * OMBU Blog Module
 *
 * Provides single-blog functionality for a drupal site. Features include:
 *   - Tags, tagging via taxonomy
 *   - Blog-only search.  Set OMBUBLOG_SEARCH to TRUE to enable
 *       To disable the normal search module callbacks (/search/node, /search/user), place
 *       the following code in a hook_menu_alter() function:
 *         unset($items['search/user/%menu_tail']);
 *         unset($items['search/node/%menu_tail']);
 *         unset($items['search']);
 */

include_once('ombublog.features.inc');

/****
 * Constants
 */
define('OMBUBLOG_BASE_PATH', 'blog'); // Base url stem for blog functionality
define('OMBUBLOG_SEARCH', TRUE); // Enable/Disable blog searching


/****
 * Includes
 */
if (OMBUBLOG_SEARCH) {
    require_once(dirname(__FILE__) . '/ombublog.search.inc');
}


/****
 * Module Hooks
 */

/**
 * Implements hook_cron().
 */
function ombublog_cron() {
  // Delete orphaned blog tags
  //$ombublog_tags_vid = variable_get('ombublog_tags_vid', 1);
  //db_query("DELETE FROM td USING {term_data} td LEFT JOIN {term_node} tn ON td.tid = tn.tid WHERE tn.tid IS NULL AND td.vid = %d", $ombublog_tags_vid);
}

/**
 * Implements hook_menu().
 */
function ombublog_menu() {
  $items = array();

  if (OMBUBLOG_SEARCH) {
    $items[OMBUBLOG_BASE_PATH . '/search'] = array(
      'page callback' => 'ombublog_search_view',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    $items[OMBUBLOG_BASE_PATH . '/search/%menu_tail'] = array(
      'page callback' => 'ombublog_search_view',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}

/**
 * Implements hook_block_info().
 */
function ombublog_block_info() {
  $blocks['archive_list'] = array(
    'info' => t('OMBU Blog Archive list'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  if (OMBUBLOG_SEARCH) {
    $blocks['search'] = array(
      'info' => t('OMBU Blog Search Form'),
      'cache' => DRUPAL_NO_CACHE,
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ombublog_block_view($delta = 0) {
  $block = array();

  switch ($delta) {
    case 'search':
      $block['subject'] = t('Search');
      $block['content'] = drupal_get_form('ombublog_search_form');
      break;
  }

  return $block;
}
